name: Budget
options:
  bundleIdPrefix: com.budget
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.10"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 2.6.0

targets:
  Budget:
    type: application
    platform: macOS
    sources:
      - Budget
    info:
      path: Budget/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.budget.app
        PRODUCT_NAME: Budget
        GENERATE_INFOPLIST_FILE: "NO"
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ENABLE_PREVIEWS: "YES"
    dependencies:
      - package: Sparkle
        product: Sparkle
    entitlements:
      path: Budget/Budget.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
    scheme:
      testPlans: []
